language: node_js
node_js:
  - "4.0"
  - "4.1"
  - "4.2"
  - "4.8"
  - "5.10"
  - "5.11"
  - "6.0"
  - "6.1"
  - "7.7"
matrix:
sudo: false
cache:
  directories:
    - node_modules
script: "npm run ci"