language: node_js
node_js:
  - "4.0"
  - "4.1"
  - "4.2"
  - "5.11"
  - "6.1"
  - "7.7"
matrix:
sudo: false
cache:
  directories:
    - node_modules
script: "npm run ci"
before_deploy:
  - npm run build
deploy:
  provider: npm
  email: ykrevnyi@gmail.com
  api_key: "$NPM_API_KEY"
  on:
    tags: true