version: '2.0'
services:

  api:
    build: .
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=test
    volumes:
      - ./:/home/app/api
      - /home/app/api/node_modules

  mongodb:
    image: mongo:3.2.8
